meta_name: "Cane Corso Records"
meta_title: "Cane Corso Records - Label, booking et évènements de musique électronique"
meta_description: "Cane Corso Records est un label nantais de musique électronique qui explore les genres et met en avant les artistes de la nouvelle scène française."
meta_image: "logosocials.png" # should exist in `app/assets/images/`
# twitter_account: "@your_twitter_account"   # required for Twitter Cards
